// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// BucketOperation represents a bucket-level breakdown of a Job.
public struct BucketOperation: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the BucketOperation. This is defined by
  /// the service. Format:
  /// projects/{project}/locations/global/jobs/{job_id}/bucketOperations/{bucket_operation}.
  public var name: Swift.String = Swift.String()

  /// The bucket name of the objects to be transformed in the BucketOperation.
  public var bucketName: Swift.String = Swift.String()

  /// Output only. The time that the BucketOperation was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The time that the BucketOperation was started.
  public var startTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The time that the BucketOperation was completed.
  public var completeTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Information about the progress of the bucket operation.
  public var counters: Counters? = nil

  /// Output only. Summarizes errors encountered with sample error log entries.
  public var errorSummaries: [ErrorSummary] = []

  /// Output only. State of the BucketOperation.
  public var state: BucketOperation.State = BucketOperation.State()

  /// Specifies objects to be transformed in the BucketOperation.
  public var objectConfiguration: OneOf_ObjectConfiguration? = nil

  /// Action to be performed on the objects.
  public var transformation: OneOf_Transformation? = nil

  /// Initialize a new instance of `BucketOperation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BucketOperation().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case bucketName = "bucketName"
    case prefixList = "prefixList"
    case manifest = "manifest"
    case putObjectHold = "putObjectHold"
    case deleteObject = "deleteObject"
    case putMetadata = "putMetadata"
    case rewriteObject = "rewriteObject"
    case updateObjectCustomContext = "updateObjectCustomContext"
    case createTime = "createTime"
    case startTime = "startTime"
    case completeTime = "completeTime"
    case counters = "counters"
    case errorSummaries = "errorSummaries"
    case state = "state"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.bucketName = try container.decode(Swift.String.self, forKey: .bucketName)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .createTime)
    self.startTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .startTime)
    self.completeTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .completeTime)
    self.counters = try container.decodeIfPresent(Counters.self, forKey: .counters)
    self.errorSummaries = try container.decode([ErrorSummary].self, forKey: .errorSummaries)
    self.state = try container.decode(BucketOperation.State.self, forKey: .state)

    var objectConfiguration: OneOf_ObjectConfiguration? = nil
    let objectConfigurationCheckAndSet = {
      if objectConfiguration != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'objectConfiguration'"))
      }
      objectConfiguration = $0
    }
    if let prefixList = try container.decodeIfPresent(PrefixList?.self, forKey: .prefixList) {
      try objectConfigurationCheckAndSet(.prefixList(prefixList))
    }
    if let manifest = try container.decodeIfPresent(Manifest?.self, forKey: .manifest) {
      try objectConfigurationCheckAndSet(.manifest(manifest))
    }
    self.objectConfiguration = objectConfiguration

    var transformation: OneOf_Transformation? = nil
    let transformationCheckAndSet = {
      if transformation != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'transformation'"))
      }
      transformation = $0
    }
    if let putObjectHold = try container.decodeIfPresent(
      PutObjectHold?.self, forKey: .putObjectHold)
    {
      try transformationCheckAndSet(.putObjectHold(putObjectHold))
    }
    if let deleteObject = try container.decodeIfPresent(DeleteObject?.self, forKey: .deleteObject) {
      try transformationCheckAndSet(.deleteObject(deleteObject))
    }
    if let putMetadata = try container.decodeIfPresent(PutMetadata?.self, forKey: .putMetadata) {
      try transformationCheckAndSet(.putMetadata(putMetadata))
    }
    if let rewriteObject = try container.decodeIfPresent(
      RewriteObject?.self, forKey: .rewriteObject)
    {
      try transformationCheckAndSet(.rewriteObject(rewriteObject))
    }
    if let updateObjectCustomContext = try container.decodeIfPresent(
      UpdateObjectCustomContext?.self, forKey: .updateObjectCustomContext)
    {
      try transformationCheckAndSet(.updateObjectCustomContext(updateObjectCustomContext))
    }
    self.transformation = transformation
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.bucketName, forKey: .bucketName)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.startTime, forKey: .startTime)
    try container.encode(self.completeTime, forKey: .completeTime)
    try container.encode(self.counters, forKey: .counters)
    try container.encode(self.errorSummaries, forKey: .errorSummaries)
    try container.encode(self.state, forKey: .state)

    if let choice = self.objectConfiguration {
      switch choice {
      case .prefixList(let value):
        try container.encode(value, forKey: .prefixList)
      case .manifest(let value):
        try container.encode(value, forKey: .manifest)
      }
    }

    if let choice = self.transformation {
      switch choice {
      case .putObjectHold(let value):
        try container.encode(value, forKey: .putObjectHold)
      case .deleteObject(let value):
        try container.encode(value, forKey: .deleteObject)
      case .putMetadata(let value):
        try container.encode(value, forKey: .putMetadata)
      case .rewriteObject(let value):
        try container.encode(value, forKey: .rewriteObject)
      case .updateObjectCustomContext(let value):
        try container.encode(value, forKey: .updateObjectCustomContext)
      }
    }
  }

  /// Describes state of the BucketOperation.
  public enum State: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// Created but not yet started.
    case queued
    /// In progress.
    case running
    /// Completed successfully.
    case succeeded
    /// Cancelled by the user.
    case canceled
    /// Terminated due to an unrecoverable failure.
    case failed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .queued: return 1
      case .running: return 2
      case .succeeded: return 3
      case .canceled: return 4
      case .failed: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .queued: return "QUEUED"
      case .running: return "RUNNING"
      case .succeeded: return "SUCCEEDED"
      case .canceled: return "CANCELED"
      case .failed: return "FAILED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "QUEUED": self = .queued
      case "RUNNING": self = .running
      case "SUCCEEDED": self = .succeeded
      case "CANCELED": self = .canceled
      case "FAILED": self = .failed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .queued
      case 2: self = .running
      case 3: self = .succeeded
      case 4: self = .canceled
      case 5: self = .failed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .queued: return try container.encode(1)
      case .running: return try container.encode(2)
      case .succeeded: return try container.encode(3)
      case .canceled: return try container.encode(4)
      case .failed: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Specifies objects to be transformed in the BucketOperation.
  public enum OneOf_ObjectConfiguration: Codable, Equatable, Sendable {
    /// Specifies objects matching a prefix set.
    indirect case prefixList(PrefixList?)
    /// Specifies objects in a manifest file.
    indirect case manifest(Manifest?)
  }

  /// Action to be performed on the objects.
  public enum OneOf_Transformation: Codable, Equatable, Sendable {
    /// Changes object hold status.
    indirect case putObjectHold(PutObjectHold?)
    /// Delete objects.
    indirect case deleteObject(DeleteObject?)
    /// Updates object metadata. Allows updating fixed-key and custom metadata
    /// and fixed-key metadata i.e. Cache-Control, Content-Disposition,
    /// Content-Encoding, Content-Language, Content-Type, Custom-Time.
    indirect case putMetadata(PutMetadata?)
    /// Rewrite the object and updates metadata like KMS key.
    indirect case rewriteObject(RewriteObject?)
    /// Update object custom context.
    indirect case updateObjectCustomContext(UpdateObjectCustomContext?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.storagebatchoperations.v1.BucketOperation"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
