// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Describes details about the progress of the job.
public struct Counters: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. Number of objects listed.
  public var totalObjectCount: Swift.Int64 = Swift.Int64()

  /// Output only. Number of objects completed.
  public var succeededObjectCount: Swift.Int64 = Swift.Int64()

  /// Output only. The number of objects that failed due to user errors or
  /// service errors.
  public var failedObjectCount: Swift.Int64 = Swift.Int64()

  /// Output only. Number of bytes found from source. This field is only
  /// populated for jobs with a prefix list object configuration.
  public var totalBytesFound: Swift.Int64? = nil

  /// Output only. Number of object custom contexts created. This field is only
  /// populated for jobs with the UpdateObjectCustomContext transformation.
  public var objectCustomContextsCreated: Swift.Int64? = nil

  /// Output only. Number of object custom contexts deleted. This field is only
  /// populated for jobs with the UpdateObjectCustomContext transformation.
  public var objectCustomContextsDeleted: Swift.Int64? = nil

  /// Output only. Number of object custom contexts updated. This counter tracks
  /// custom contexts where the key already existed, but the payload was
  /// modified. This field is only populated for jobs with the
  /// UpdateObjectCustomContext transformation.
  public var objectCustomContextsUpdated: Swift.Int64? = nil

  /// Initialize a new instance of `Counters`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Counters().with { $0.totalObjectCount = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.storagebatchoperations.v1.Counters"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
