// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Describes options to delete an object.
public struct DeleteObject: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Controls deletion behavior when versioning is enabled for the
  /// object's bucket. If true both live and noncurrent objects will be
  /// permanently deleted. Otherwise live objects in versioned buckets will
  /// become noncurrent and objects that were already noncurrent will be skipped.
  /// This setting doesn't have any impact on the Soft Delete feature. All
  /// objects deleted by this service can be be restored for the duration of the
  /// Soft Delete retention duration if enabled. If enabled and the manifest
  /// doesn't specify an object's generation, a GetObjectMetadata call (a Class B
  /// operation) will be made to determine the live object generation.
  public var permanentObjectDeletionEnabled: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `DeleteObject`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DeleteObject().with { $0.permanentObjectDeletionEnabled = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.storagebatchoperations.v1.DeleteObject"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
