// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The Storage Batch Operations Job description.
public struct Job: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the Job. job_id is unique
  /// within the project, that is either set by the customer or
  /// defined by the service. Format:
  /// projects/{project}/locations/global/jobs/{job_id} .
  /// For example: "projects/123456/locations/global/jobs/job01".
  public var name: Swift.String = Swift.String()

  /// Optional. A description provided by the user for the job. Its max length is
  /// 1024 bytes when Unicode-encoded.
  public var description: Swift.String = Swift.String()

  /// Optional. Logging configuration.
  public var loggingConfig: LoggingConfig? = nil

  /// Output only. The time that the job was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time that the job was scheduled.
  public var scheduleTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time that the job was completed.
  public var completeTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Information about the progress of the job.
  public var counters: Counters? = nil

  /// Output only. Summarizes errors encountered with sample error log entries.
  public var errorSummaries: [ErrorSummary] = []

  /// Output only. State of the job.
  public var state: Job.State = Job.State()

  /// Optional. If true, the job will run in dry run mode, returning the total
  /// object count and, if the object configuration is a prefix list, the bytes
  /// found from source. No transformations will be performed.
  public var dryRun: Swift.Bool = Swift.Bool()

  /// Output only. If true, this Job operates on multiple buckets. Multibucket
  /// jobs are subject to different quota limits than single-bucket jobs.
  public var isMultiBucketJob: Swift.Bool = Swift.Bool()

  /// Specifies objects to be transformed.
  public var source: OneOf_Source? = nil

  /// Operation to be performed on the objects.
  public var transformation: OneOf_Transformation? = nil

  /// Initialize a new instance of `Job`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Job().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case description = "description"
    case bucketList = "bucketList"
    case putObjectHold = "putObjectHold"
    case deleteObject = "deleteObject"
    case putMetadata = "putMetadata"
    case rewriteObject = "rewriteObject"
    case updateObjectCustomContext = "updateObjectCustomContext"
    case loggingConfig = "loggingConfig"
    case createTime = "createTime"
    case scheduleTime = "scheduleTime"
    case completeTime = "completeTime"
    case counters = "counters"
    case errorSummaries = "errorSummaries"
    case state = "state"
    case dryRun = "dryRun"
    case isMultiBucketJob = "isMultiBucketJob"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.description = try container.decode(Swift.String.self, forKey: .description)
    self.loggingConfig = try container.decodeIfPresent(LoggingConfig.self, forKey: .loggingConfig)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .createTime)
    self.scheduleTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .scheduleTime)
    self.completeTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .completeTime)
    self.counters = try container.decodeIfPresent(Counters.self, forKey: .counters)
    self.errorSummaries = try container.decode([ErrorSummary].self, forKey: .errorSummaries)
    self.state = try container.decode(Job.State.self, forKey: .state)
    self.dryRun = try container.decode(Swift.Bool.self, forKey: .dryRun)
    self.isMultiBucketJob = try container.decode(Swift.Bool.self, forKey: .isMultiBucketJob)

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let bucketList = try container.decodeIfPresent(BucketList?.self, forKey: .bucketList) {
      try sourceCheckAndSet(.bucketList(bucketList))
    }
    self.source = source

    var transformation: OneOf_Transformation? = nil
    let transformationCheckAndSet = {
      if transformation != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'transformation'"))
      }
      transformation = $0
    }
    if let putObjectHold = try container.decodeIfPresent(
      PutObjectHold?.self, forKey: .putObjectHold)
    {
      try transformationCheckAndSet(.putObjectHold(putObjectHold))
    }
    if let deleteObject = try container.decodeIfPresent(DeleteObject?.self, forKey: .deleteObject) {
      try transformationCheckAndSet(.deleteObject(deleteObject))
    }
    if let putMetadata = try container.decodeIfPresent(PutMetadata?.self, forKey: .putMetadata) {
      try transformationCheckAndSet(.putMetadata(putMetadata))
    }
    if let rewriteObject = try container.decodeIfPresent(
      RewriteObject?.self, forKey: .rewriteObject)
    {
      try transformationCheckAndSet(.rewriteObject(rewriteObject))
    }
    if let updateObjectCustomContext = try container.decodeIfPresent(
      UpdateObjectCustomContext?.self, forKey: .updateObjectCustomContext)
    {
      try transformationCheckAndSet(.updateObjectCustomContext(updateObjectCustomContext))
    }
    self.transformation = transformation
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.loggingConfig, forKey: .loggingConfig)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.scheduleTime, forKey: .scheduleTime)
    try container.encode(self.completeTime, forKey: .completeTime)
    try container.encode(self.counters, forKey: .counters)
    try container.encode(self.errorSummaries, forKey: .errorSummaries)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.dryRun, forKey: .dryRun)
    try container.encode(self.isMultiBucketJob, forKey: .isMultiBucketJob)

    if let choice = self.source {
      switch choice {
      case .bucketList(let value):
        try container.encode(value, forKey: .bucketList)
      }
    }

    if let choice = self.transformation {
      switch choice {
      case .putObjectHold(let value):
        try container.encode(value, forKey: .putObjectHold)
      case .deleteObject(let value):
        try container.encode(value, forKey: .deleteObject)
      case .putMetadata(let value):
        try container.encode(value, forKey: .putMetadata)
      case .rewriteObject(let value):
        try container.encode(value, forKey: .rewriteObject)
      case .updateObjectCustomContext(let value):
        try container.encode(value, forKey: .updateObjectCustomContext)
      }
    }
  }

  /// Describes state of a job.
  public enum State: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// In progress.
    case running
    /// Completed successfully.
    case succeeded
    /// Cancelled by the user.
    case canceled
    /// Terminated due to an unrecoverable failure.
    case failed
    /// Queued but not yet started.
    case queued
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .running: return 1
      case .succeeded: return 2
      case .canceled: return 3
      case .failed: return 4
      case .queued: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .running: return "RUNNING"
      case .succeeded: return "SUCCEEDED"
      case .canceled: return "CANCELED"
      case .failed: return "FAILED"
      case .queued: return "QUEUED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "RUNNING": self = .running
      case "SUCCEEDED": self = .succeeded
      case "CANCELED": self = .canceled
      case "FAILED": self = .failed
      case "QUEUED": self = .queued
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .running
      case 2: self = .succeeded
      case 3: self = .canceled
      case 4: self = .failed
      case 5: self = .queued
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .running: return try container.encode(1)
      case .succeeded: return try container.encode(2)
      case .canceled: return try container.encode(3)
      case .failed: return try container.encode(4)
      case .queued: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Specifies objects to be transformed.
  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// Specifies a list of buckets and their objects to be transformed.
    indirect case bucketList(BucketList?)
  }

  /// Operation to be performed on the objects.
  public enum OneOf_Transformation: Codable, Equatable, Sendable {
    /// Changes object hold status.
    indirect case putObjectHold(PutObjectHold?)
    /// Delete objects.
    indirect case deleteObject(DeleteObject?)
    /// Updates object metadata. Allows updating fixed-key and custom metadata
    /// and fixed-key metadata i.e. Cache-Control, Content-Disposition,
    /// Content-Encoding, Content-Language, Content-Type, Custom-Time.
    indirect case putMetadata(PutMetadata?)
    /// Rewrite the object and updates metadata like KMS key.
    indirect case rewriteObject(RewriteObject?)
    /// Update object custom context.
    indirect case updateObjectCustomContext(UpdateObjectCustomContext?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.storagebatchoperations.v1.Job"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
