// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Describes list of objects to be transformed.
public struct Manifest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. `manifest_location` must contain the manifest source file that is
  /// a CSV file in a Google Cloud Storage bucket. Each row in the file must
  /// include the object details i.e. BucketId and Name. Generation may
  /// optionally be specified. When it is not specified the live object is acted
  /// upon. `manifest_location` should either be 1) An absolute path to the
  /// object in the format of `gs://bucket_name/path/file_name.csv`. 2) An
  /// absolute path with a single wildcard character in the file name, for
  /// example `gs://bucket_name/path/file_name*.csv`.
  /// If manifest location is specified with a wildcard, objects in all manifest
  /// files matching the pattern will be acted upon.
  public var manifestLocation: Swift.String = Swift.String()

  /// Initialize a new instance of `Manifest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Manifest().with { $0.manifestLocation = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.storagebatchoperations.v1.Manifest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
