// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Describes options for object metadata update.
public struct PutMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. Updates objects Content-Disposition fixed metadata. Unset values
  /// will be ignored. Set empty values to clear the metadata. Refer
  /// https://cloud.google.com/storage/docs/metadata#content-disposition for
  /// additional documentation.
  public var contentDisposition: Swift.String? = nil

  /// Optional. Updates objects Content-Encoding fixed metadata. Unset values
  /// will be ignored. Set empty values to clear the metadata. Refer to
  /// documentation in
  /// https://cloud.google.com/storage/docs/metadata#content-encoding.
  public var contentEncoding: Swift.String? = nil

  /// Optional. Updates objects Content-Language fixed metadata. Refer to ISO
  /// 639-1 language codes for typical values of this metadata. Max length 100
  /// characters. Unset values will be ignored. Set empty values to clear the
  /// metadata. Refer to documentation in
  /// https://cloud.google.com/storage/docs/metadata#content-language.
  public var contentLanguage: Swift.String? = nil

  /// Optional. Updates objects Content-Type fixed metadata. Unset values will be
  /// ignored. Set empty values to clear the metadata. Refer to documentation in
  /// https://cloud.google.com/storage/docs/metadata#content-type
  public var contentType: Swift.String? = nil

  /// Optional. Updates objects Cache-Control fixed metadata. Unset values will
  /// be ignored. Set empty values to clear the metadata. Additionally, the value
  /// for Custom-Time cannot decrease. Refer to documentation in
  /// https://cloud.google.com/storage/docs/metadata#caching_data.
  public var cacheControl: Swift.String? = nil

  /// Optional. Updates objects Custom-Time fixed metadata. Unset values will be
  /// ignored. Set empty values to clear the metadata. Refer to documentation in
  /// https://cloud.google.com/storage/docs/metadata#custom-time.
  public var customTime: Swift.String? = nil

  /// Optional. Updates objects custom metadata. Adds or sets individual custom
  /// metadata key value pairs on objects. Keys that are set with empty custom
  /// metadata values will have its value cleared. Existing custom metadata not
  /// specified with this flag is not changed. Refer to documentation in
  /// https://cloud.google.com/storage/docs/metadata#custom-metadata
  public var customMetadata: [Swift.String: Swift.String] = [:]

  /// Optional. Updates objects retention lock configuration. Unset values will
  /// be ignored. Set empty values to clear the retention for the object with
  /// existing `Unlocked` retention mode. Object with existing `Locked` retention
  /// mode cannot be cleared or reduce retain_until_time. Refer to documentation
  /// in https://cloud.google.com/storage/docs/object-lock
  public var objectRetention: ObjectRetention? = nil

  /// Initialize a new instance of `PutMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PutMetadata().with { $0.contentDisposition = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.storagebatchoperations.v1.PutMetadata"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
