// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Describes options to update object custom contexts.
public struct UpdateObjectCustomContext: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// One of the actions must be set.
  public var action: OneOf_Action? = nil

  /// Initialize a new instance of `UpdateObjectCustomContext`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateObjectCustomContext().with { $0.customContextUpdates = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case customContextUpdates = "customContextUpdates"
    case clearAll = "clearAll"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var action: OneOf_Action? = nil
    let actionCheckAndSet = {
      if action != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'action'"))
      }
      action = $0
    }
    if let customContextUpdates = try container.decodeIfPresent(
      CustomContextUpdates?.self, forKey: .customContextUpdates)
    {
      try actionCheckAndSet(.customContextUpdates(customContextUpdates))
    }
    if let clearAll = try container.decodeIfPresent(Swift.Bool.self, forKey: .clearAll) {
      try actionCheckAndSet(.clearAll(clearAll))
    }
    self.action = action
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.action {
      switch choice {
      case .customContextUpdates(let value):
        try container.encode(value, forKey: .customContextUpdates)
      case .clearAll(let value):
        try container.encode(value, forKey: .clearAll)
      }
    }
  }

  /// One of the actions must be set.
  public enum OneOf_Action: Codable, Equatable, Sendable {
    /// A collection of updates to apply to specific custom contexts.
    /// Use this to add, update or delete individual contexts by key.
    indirect case customContextUpdates(CustomContextUpdates?)
    /// If set, must be set to true and all existing object custom contexts will
    /// be deleted.
    case clearAll(Swift.Bool)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.storagebatchoperations.v1.UpdateObjectCustomContext"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
